# Generated by Django 6.0.5 on 2026-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('GRANO', 'Grano'), ('FRUTA', 'Fruta'), ('VERDURA', 'Verdura'), ('TUBERCULO', 'Tubérculo'), ('LEGUMBRE', 'Legumbre')], default='VERDURA', max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('temporada_siembra', models.CharField(choices=[('PRIMAVERA', 'Primavera'), ('VERANO', 'Verano'), ('OTOÑO', 'Otoño'), ('INVIERNO', 'Invierno'), ('TODO_EL_AÑO', 'Todo el año')], default='PRIMAVERA', max_length=20)),
                ('temporada_cosecha', models.CharField(choices=[('PRIMAVERA', 'Primavera'), ('VERANO', 'Verano'), ('OTOÑO', 'Otoño'), ('INVIERNO', 'Invierno'), ('TODO_EL_AÑO', 'Todo el año')], default='VERANO', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
